### ISSUE TITLE
swagger-ui is missing in docker build

### ISSUE THREAD

**Issue by rcemper** [lscalese/openapi-suite#1]
I tried to add it to iris.script
that failed with various version dependencies in ZPM
````
failed to solve: executor failed running [/bin/sh -c iris start IRIS &&         iris session IRIS < iris.script &&
     ([ $TESTS -eq 0 ] || iris session iris -U $NAMESPACE "##class(%ZPM.PackageManager).Shell(\"test $MODULE -v -o
nly\",1,1)") &&     iris stop IRIS quietly]: exit code: 1
````
I had less problems with /iris-community:latest instead of :preview    
I didn't get it stable

**Comment by lscalese** [comment]
Hi @rcemper ,

Thank you for your report.
I change the image with the tag "latest".
I hope It will be stable.

The install of "swagger-ui" has been added in the "iris.script".
I don't add this install in the "module.xml" because it's not mandatory for the openapi-suite application :-)

**Comment by lscalese** [comment]
could you please retry with : 
```
docker-compose build --no-cache
```

**Comment by lscalese** [comment]
Hi @rcemper ,

Thank you for the error logs.
It's strange because the version for the `sslclient` dependency is 1.0.1 in `openapi-client-gen` and `openapi-server-gen`.

After the first error at the docker-build phase, I have already noticed strange behaviour on my install.
The build failed any time until : 

```
docker system prune
docker-compose build --no-cache
```
Maybe a `docker image prune` is enough.

Could you try this?

If the problem persists, I will push a new version tag like this in `openapi-client-gen` and `openapi-server-gen`: 
```
        <ModuleReference>
          <Name>io-redirect</Name>
          <Version>1.0.*</Version>
        </ModuleReference>
```

Keep me posted.
Thank you.

Lorenzo.

**Comment by rcemper** [comment]
Confirmed !  Builds without any intervention
````
#7 67.36     iKnowEnabled: 0
#7 67.36 Done.
#7 67.36 ☺chmod♦☺-R♣☺775#☺/usr/irissys/csp/openapisuite/ui/
#7 67.37 ☺chmod♦☺-R♣☺775#☺/usr/irissys/csp/openapisuite/ui/
#7 67.37 Clearing CSPGateway cache of /openapisuite/ui/*
#7 67.37 [IRISAPP|openapi-suite]        Configure SUCCESS
#7 67.40 Studio project created/updated: openapi-suite.PRJ
#7 67.40 [IRISAPP|openapi-suite]        Activate SUCCESS#7 DONE 72.2s

#8 exporting to image
#8 exporting layers
#8 exporting layers 8.3s done
#8 writing image sha256:0659355a25f63f0ef087dcf2bc3530c8b30973c1748ed69bad9b0e660220fa6e 0.0s done
#8 naming to docker.io/library/openapi-suite-iris 0.0s done
#8 DONE 8.4s
````
THANKS & Congratulations

**Comment by lscalese** [comment]
Great !
Thank you very much for your feedback @rcemper
