### ISSUE TITLE
Allow suppressing of required qualifier, instead add “required” as part of description!

### ISSUE THREAD

**Issue by isc-tstolker** [lscalese/openapi-suite#17]
I just ran into a case where an openapi spec had a lot of "required" properties in the request model, however, the software offering the API did not comply to this themselves, causing our requests to fail.

I would like to be able to override generation of required properties so that "required" is added to the description instead of as a qualifier.

**Comment by lscalese** [comment]
@isc-tstolker ,

I also experienced this kind of error due to a specification that did not match with the API.
If the specification specifies "required", we have to generate a required property.

**Comment by lscalese** [comment]
I just change something in model generation to do this, result example : 

```objectscript
/// 
/// * This property is required.
Property id As %String(MAXLEN = "");

/// A map containing service references and/or endpoints.
/// * This property is required.
Property serviceEndpoint As Nuts.Api.DidManager.model.CompoundServiceserviceEndpoint;

/// type of the endpoint. May be freely chosen.
/// * This property is required.
Property type As %String(MAXLEN = "");

```

To change the behavior, we have to set the features: 

```objectscript
    set features("model.property.norequired")=1
```

Please change the entry point:

```
set sc = ##class(dc.openapi.client.Spec).generateApp(packageName, url, .features, externals)
; to 
Set sc = ##class(dc.openapi.suite.Generate).ProductionClient(packageName, url, .features, externals)
```

`generateApp` won't work with "model.property.norequired" and I would like to gather all entry generation point in the class `dc.openapi.suite.Generate`.

**Comment by isc-tstolker** [comment]
Super, that looks awesome!!

**Comment by isc-tstolker** [comment]
Great, works nice!!
