### ISSUE TITLE
Add support for "application/x-www-form-urlencoded"; generate new utility class util.UrlEncodedRequest 

### ISSUE THREAD

**Issue by isc-tstolker** [lscalese/openapi-suite#18]
Requests with content-type "application/x-www-form-urlencoded" are not currently supported.
It is straightforward to create a url-encoded body from a json request.
This requires a utility class named utility util.UrlEncodedRequest to be generated.
I propose that we allow generating this in a common package.

**Comment by isc-tstolker** [comment]
I am already implementing this, PR to be coming soon!

**Comment by lscalese** [comment]
Thank you @isc-tstolker !

**Comment by isc-tstolker** [comment]
Hi @lscalese , I had to move the code portion created for setting the initial value of %ContentType, otherwise the method body for post requests turned up empty

**Comment by lscalese** [comment]
No problem @isc-tstolker !
Please let me know if there is a missing class on the repo.  After accepting the merge, I noticed the referenced class in this line does not exist on the repository:

```objectscript
Set clsUtils = ##class(%Dictionary.ClassDefinition).%OpenId("dc.openapi.client.UrlEncodedRequest").%ConstructClone()
```
maybe a forgotten commit.
Thank you

**Comment by isc-tstolker** [comment]
I have just added the class, indeed I forgot to commit that!
