### ISSUE TITLE
Request processing: Give content-type an initial value and/or raise an error if no request was added

### ISSUE THREAD

**Issue by isc-tstolker** [lscalese/openapi-suite#19]
When using a request class generated bij openapi-suite associated with a POST, the creator of the  request message has to explicitly set the content-type. 

I guess it may even required for GETs if your server is picky :)

This is confusing and not right if you view the generated Business Operation as a Black box.
Also, it leads to unexpected ill behavior in case of POST, as an empty body is submitted by the API

So the generated request class should either set the Content-Type as the initial value, like in

`Property %ContentType As %String [ InitialExpression = "application/json" ];`

And/or the LoadHttpRequestObject() method should quit with an error when no matching content-type is found, like in:

```
/// Load %Net.HttpRequest with this property object.
Method LoadHttpRequestObject(ByRef httpRequest As %Net.HttpRequest) As %Status
{
	Set sc = $$$OK
	Set httpRequest.ContentType = ..%ContentType
	Do httpRequest.SetHeader("accept", ..%Consume)
	Set ..%URL = $Replace(..%URL,"{did}", ..pathdid)
	If $Piece($$$LOWER(..%ContentType),";",1) = "application/json" {
           Do ..ContactInformation.%JSONExportToStream(httpRequest.EntityBody)
           return sc
        }
	return $SYSTEM.Status.Error($$$GeneralError, "No matching content-type found; found '" _ ..%ContentType _ "'")
}
```

**Comment by lscalese** [comment]
Hi @isc-tstolker,

I'm ok to set `%ContentType` to `application/json`, today this is the most commonly used.
I assign the task to myself.

**Comment by lscalese** [comment]
@isc-tstolker Finally, I set the `InitialExpression` with the first content type found for this request.
Even If `application/json` is commonly used, sometimes we use another. 
If you are ok, we can close this issue.

**Comment by isc-tstolker** [comment]
Looks awesome, thanks!
