### ISSUE TITLE
Request classes - Add MAXLEN="" for path properties and %URL

### ISSUE THREAD

**Issue by isc-tstolker** [lscalese/openapi-suite#20]
In one of my APIs the value for a path property was a DID with length > 50, which caused the API to fail.
I recommend that also path properties are generated with a MAXLEN = "".
Subsequently, the %URL should also have a MAXLEN = "" qualifier!

**Comment by lscalese** [comment]
Hi @isc-tstolker !

Thank you for this report.
It's resolved.

It will be included in the next package version.

**Comment by isc-tstolker** [comment]
Hi @lscalese ,

The Path variable indeed has the MAXLEN= "", but the %URL has not:

```
Property %URL As %String [ InitialExpression = {..#URL} ];

/// Use this property for body content with content-type = application/json.
Property ContactInformation As Nuts.Api.DidManager.model.ContactInformation;

/// URL encoded DID.
Property pathdid As %String(MAXLEN = "");

```

**Comment by lscalese** [comment]
I don't understand how it's possible, do you have this bloc of code in `src/dc/openapi/common/Generator.cls` : 

```objectscript
/// Add property %URL
    Set propertyName = "%URL", propDef = $$$FindPropertyName(classDef, propertyName)
    Set:'$IsObject(propDef) propDef = ##class(%Dictionary.PropertyDefinition).%New(classDef.Name _ ":" _ propertyName )
    Set propDef.Type = "%String", propDef.InitialExpression = "..#URL"
    $$$zlog($Char(9) _ "+ SET MAXLEN " _ propertyName)
    Do propDef.Parameters.SetAt("","MAXLEN")
    $$$zlog($Char(9) _ "+ Add property " _ propertyName)
    Do classDef.Properties.Insert(propDef)
```

**Comment by isc-tstolker** [comment]
Hi @lscalese,

It look like it was my mistake; after updating the repo I did not compile this class.

Thanks!
