### ISSUE TITLE
Better handling of %URL in Request class

### ISSUE THREAD

**Issue by isc-tstolker** [lscalese/openapi-suite#21]
Right now, when a Request Url has a path variable, it is generated as:

```
	Set ..%URL = $Replace(..%URL,"{did}", ..pathdid)
```
This works OK when you use the request class once, because %URL has an InitialExpression:

```
Property %URL As %String [ InitialExpression = {..#URL} ];
```

However, if anyone would ever try to reuse the same request class with a different path variable, the second request will not do what is expected!

Therefore, why not generate the formatting of the path as:

```
	Set ..%URL = $Replace(..#URL,"{did}", ..pathdid)
```

The only caveat is that would prevent clients from changing the URL property. Is that something you would expect clients to do?

**Comment by lscalese** [comment]
Indeed!

I don't have any problem using `..#URL` to reuse easily.   
I'll push a change.

**Comment by lscalese** [comment]
Done.
