### ISSUE TITLE
Allow generating GenericReponse as common message

### ISSUE THREAD

**Issue by isc-tstolker** [lscalese/openapi-suite#22]
When using multiple APIs in the same solution, you will see multiple copies of the GenericResponse being generated.
I propose that we allow specifying that GenericResponse is generated in a common package.

**Comment by isc-tstolker** [comment]
@lscalese , pull request is waiting!

**Comment by lscalese** [comment]
Thank you @isc-tstolker !
I just accepted the pull request.

By the way, I implemented small utils methods to store temp data in a variable %z
It could be useful if you need to store a parameter and use it later in the code generation process.

```
##class(dc.openapi.common.Utils).SetTempData("my.param.key","paramvalue")
##class(dc.openapi.common.Utils).GetTempData("my.param.key")
```

**Comment by isc-tstolker** [comment]
Thanks, @lscalese
