### ISSUE TITLE
version mismath with ZPM

### ISSUE THREAD

**Issue by rcemper** [lscalese/openapi-suite#3]
ERROR! Download module 'yaml-utils@0.1.1', something went wrong (StatusCode: ).

version has changed:
````
zpm:USER>search yaml-utils
registry https://pm.community.intersystems.com:
yaml-utils 0.1.2
````

**Comment by lscalese** [comment]
Hi @rcemper ,

I will change with a star  in my different project to avoid this.

**Comment by rcemper** [comment]
confirm. ussie is solved !
congratulations !
